### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by prashant00797** [nitinkathpalia09/Mouse_control#1]
i used default calibaration and got this error..
Traceback (most recent call last):
  File "C:\Users\X\Downloads\Mouse_control-master\Mouse_control-master\mouse.py", line 330, in <module>
    b_cen = drawCentroid( frame, b_area, b_mask, showCentroid)
  File "C:\Users\X\Downloads\Mouse_control-master\Mouse_control-master\mouse.py", line 91, in drawCentroid
    _, contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by BalveerSinghYT** [comment]
I also got the same error.

**Comment by AdopaX** [comment]
I get this error too
please help! (:

**Comment by Ranjesh232** [comment]
same error...
how to solve??

**Comment by phi19** [comment]
I am not the developer, so I don't know if this is working the way it should. 
Having said that...

At the line 92 it is written `_, contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`
And it should be written `contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

This got me our of the error. I hope I helped :)
