### ISSUE TITLE
how to solve this error sir

### ISSUE THREAD

**Issue by eshwar5622** [nitinkathpalia09/Mouse_control#2]
C:\Users\eshwar\PycharmProjects\cv1\venv\Scripts\python.exe C:/Users/eshwar/PycharmProjects/cv1/pract1.py
**********************************************************************
 You have entered calibration mode.
 Use the trackbars to calibrate and press SPACE when done.
 Press D to use the default settings.
**********************************************************************
 Calibration Successfull...
**********************************************************************
 Press P to turn ON and OFF mouse simulation.
 Press C to display the centroid of various colours.
 Press R to recalibrate color ranges.
 Press ESC to exit.
**********************************************************************

######after this , the error is shown up and video is getting of#####

Traceback (most recent call last):
  File "C:/Users/eshwar/PycharmProjects/cv1/pract1.py", line 329, in <module>
    b_cen = drawCentroid(frame, b_area, b_mask, showCentroid)
  File "C:/Users/eshwar/PycharmProjects/cv1/pract1.py", line 88, in drawCentroid
    _, contour, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

Process finished with exit code 1

**Comment by phi19** [comment]
I am not the developer, so I don't know if this is working the way it should. 
Having said that...

At the line 92 it is written `_, contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`
And it should be written `contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

This got me our of the error. I hope I helped :)

**Comment by ABG-SHAILESH** [comment]
Use open-cv version 4.3 Or below that

After that 
At the line 92 it is written _, contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
And it should be written contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
